export const GET_ARTIST_FEED_TAKE_DEFAULT = 50;
export const GET_ARTISTS_TAKE_DEFAULT = 250;
export const SEARCH_ARTISTS_TAKE_DEFAULT = 50;
export const GET_ARTIST_TRACKS_TAKE_DEFAULT = 100;
export const GET_ARTIST_BLURBS_TAKE_DEFAULT = 10;
export const GET_ARTIST_BLURBS_DAYS_LIMIT = 90; // days
export const GET_ARTIST_BUZZ_CHART_DAYS_LIMIT = 90; // days
