export const ErrorConst = {
  BRACKHIT_NOT_FOUND: 'BRACKHIT_NOT_FOUND',
  DATE_QUERY_PARAM_REQUIRED: 'DATE_QUERY_PARAM_REQUIRED',
  // friend requests
  FRIEND_REQUEST_TO_HIMSELF: 'FRIEND_REQUEST_TO_HIMSELF',
  ALREADY_SENT_REQUEST: 'ALREADY_SENT_REQUEST',
  ALREADY_ACCEPTED_REQUEST: 'ALREADY_ACCEPTED_REQUEST',
  PENDING_INCOMING_REQUEST: 'PENDING_INCOMING_REQUEST',
  FRIEND_REQUEST_NOT_SENT: 'FRIEND_REQUEST_NOT_SENT',
  NO_PENDING_REQUESTS: 'NO_PENDING_REQUESTS',
  SEARCH_QUERY_IS_TOO_SHORT: 'SEARCH_QUERY_IS_TOO_SHORT',
  USERS_ARE_NOT_FRIENDS: 'USERS_ARE_NOT_FRIENDS',
  USERS_ARE_ALREADY_FRIENDS: 'USERS_ARE_ALREADY_FRIENDS',

  // user
  AWS_USER_DOES_NOT_EXIST: 'AWS_USER_DOES_NOT_EXIST',
  USER_PROFILE_DOES_NOT_EXISTS: 'USER_PROFILE_DOES_NOT_EXISTS',
};
