export enum ScheduledTaskType {
  SUGGEST_NEW_BRACKHIT_NOTIFICATION = 'SUGGEST_NEW_BRACKHIT_NOTIFICATION',
  BRACKHIT_CHALLENGE_WINNER_NOTIFICATION = 'BRACKHIT_CHALLENGE_WINNER_NOTIFICATION',
  ALL_PENDING_REQUESTS_NOTIFICATION_JOB = 'ALL_PENDING_REQUESTS_NOTIFICATION_JOB',
}
