import { ApiProperty } from '@nestjs/swagger';

export class CampaignSummaryOutput {
  @ApiProperty({ description: 'Total number of unique visitors to the campaign', example: 14695 })
  uniqueVisitors: number;

  @ApiProperty({ description: 'Total number of submissions received', example: 11794 })
  submissions: number;

  @ApiProperty({ description: 'Average length of user sessions', example: 2.08 })
  averageSessionTime: number;

  // @ApiProperty({ description: 'Percentage of users who bounced (left after viewing only one page)', example: 23 })
  // bounceRate: number;
  //
  // @ApiProperty({ description: 'Percentage of users who scrolled through the content', example: 48 })
  // scrollRate: number;

  @ApiProperty({ description: 'K-factor, representing viral growth of the campaign', example: 0.067 })
  kFactor: number;

  @ApiProperty({ description: 'Total number of shares across all platforms', example: 5293 })
  shares: number;

  @ApiProperty({ description: 'Total number of referrals generated by users', example: 789 })
  referrals: number;

  @ApiProperty({ description: 'Total number of custom button clicks by users', example: 2504 })
  customButtonClicks: number;

  @ApiProperty({ description: 'Total number of product clicks in the campaign', example: 0 })
  productClicks: number;
}
